"""empty message

Revision ID: db3bb59fe369
Revises: 41636ca2b741
Create Date: 2022-08-24 15:13:22.009130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3bb59fe369'
down_revision = '41636ca2b741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bid')
    # ### end Alembic commands ###
